a,b=map(int, input("Upisi dva cijela broja:").split())
c,d=map(float, input("Upisi dva realna broja:").split())
#e=int(c),f=int(d)
#print("Cijeli dio realnih brojeva:",e,f)
#g=round(c),h=round(d)
#print("Zaokruzeni realni brojevi:",g,h)
#i=int(bin(a)),j=int(bin(b))
#print("Cijeli brojevi kao binarni:",i,j)
#k=hex(a),l=hex(b)
#print("Cijeli  brojevi kao heksadekadski:",k,l)
m=oct(a),n=oct(b)
print("Cijeli brojevi kao oktalni:",m,n)
o=max(a,b,c,d)
print("Najveci od unesenih brojeva:",o)
p=min(a,b,c,d)
print("Najmanji od unesenih brojeva:",p)
