a,b=map(int, input("Upisi dva cijela broja:").split())
c,d=map(float, input("Upisi dva realna broja:").split())
aa=int(abs(a)),bb=int(abs(b)),cc=abs(c),dd=abs(d)
ka=sqrt(a),kb=sqrt(b),kc=sqrt(c),kd=sqrt(d)
fa=floor(a),fb=floor(c),fc=floor(c),fd=floor(d)
ca=ceil(a),cb=ceil(b),cc=ceil(c),cd=ceil(d)
print("Apsolutne vrijednosti unesenih brojeva:",aa,bb,cc,dd)
print("Korijeni unesenih brojeva:",ka,kb,kc,kd)
print("Brojevi")
